### ISSUE TITLE
bug(web): Cannot read properties of null (reading 'baseKeyEvent')

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#10099]
I was troubleshooting keymanweb.com locally with Docker when I ran into the following console error.

Was able to reproduce on the live keymanweb.com site 
https://keymanweb.com/?tier=alpha#hy,Keyboard_armenian 

(legacy Armenian keyboard)
https://keyman.com/keyboards/armenian

console error (ignoring null keyboard stub)

```
TypeError: Cannot read properties of null (reading 'baseKeyEvent')
    at i.constructKeyEvent (keyboard.ts:473:21)
    at i.constructBaseKeyEvent (activeLayout.ts:287:62)
    at i.polyfill (activeLayout.ts:239:10)
    at i.polyfill (activeLayout.ts:371:17)
    at i.polyfill (activeLayout.ts:507:17)
    at i.polyfill (activeLayout.ts:763:19)
    at i.layout (keyboard.ts:426:34)
    at t._GenerateKeyboardView (oskView.ts:777:31)
    at t.loadActiveKeyboard (oskView.ts:729:58)
    at t.set (oskView.ts:521:10)
    at t.<anonymous> (keymanEngine.ts:153:18)
    at W.emit (index.js:181:35)
    at t.<anonymous> (contextManagerBase.ts:277:12)
    at g (tslib.js:142:27)
    at Object.next (tslib.js:123:57)
    at o (tslib.js:113:62)
```

In the Chrome debugger
```

  constructKeyEvent(key: ActiveKey, device: DeviceSpec, stateKeys: StateKeyMap): KeyEvent {
    // Make a deep copy of our preconstructed key event, filling it out from there.
    const Lkc = key.baseKeyEvent;
    Lkc.device = device;
```

has key = null

**Comment by darcywong00** [comment]
No error with https://keymanweb.com/?tier=alpha#hy,Keyboard_basic_kbdarme
