### ISSUE TITLE
bug(developer): extranous layering message when there's a bad marker

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#10291]
to repro:

```xml
  <transform from="\m{lgtm}" to="ANYTHING" />
```

Issue:

```shell
k_008_transform_norm.xml - error KM00021: Markers used for matching but not defined: lgtm
k_008_transform_norm.xml - fatal KM05001: Unexpected exception: Error: Internal error: section bksp depends on uninitialized dependency vars, check ordering

Call stack:
Error: Internal error: section bksp depends on uninitialized dependency vars, check ordering
    at <anonymous> (/Users/srl295/src/keymanapp/keyman/developer/src/kmc-ldml/src/compiler/compiler.ts:185:19)
    at Array.forEach (<anonymous>)
    at LdmlKeyboardCompiler.compile (/Users/srl295/src/keymanapp/keyman/developer/src/kmc-ldml/src/compiler/compiler.ts:179:38)
    at buildLdmlKeyboardToMemory (/Users/srl295/src/keymanapp/keyman/developer/src/kmc/src/commands/buildClasses/BuildLdmlKeyboard.ts:60:13)
    at BuildLdmlKeyboard.build (/Users/srl295/src/keymanapp/keyman/developer/src/kmc/src/commands/buildClasses/BuildLdmlKeyboard.ts:16:25)
    at build (/Users/srl295/src/keymanapp/keyman/developer/src/kmc/src/commands/build.ts:154:18)
    at Command.<anonymous> (/Users/srl295/src/keymanapp/keyman/developer/src/kmc/src/commands/build.ts:83:13)
    at async Command.parseAsync (/Users/srl295/src/keymanapp/keyman/node_modules/commander/lib/command.js:935:5)
    at run (/Users/srl295/src/keymanapp/keyman/developer/src/kmc/src/kmc.ts:58:3)
    at <anonymous> (/Users/srl295/src/keymanapp/keyman/developer/src/kmc/src/kmc.ts:14:3)

    This error has been automatically reported to the Keyman team.
      Identifier:  84dc0e9746634ad1be4e2ec447b62b62
      Application: Keyman Developer
      Reported at: https://sentry.io/organizations/keyman/projects/keyman-developer/events/84dc0e9746634ad1be4e2ec447b62b62/
```

So what happened is that the `vars` section couldn't init due to the error.  But this appeared as a _dependency_ error, showing the internal err `KM05001`

We should track when a section fails to init with an error, and not show the dependency message.

**Comment by srl295** [comment]
Also the message should be something like the following, because unused keys aren't considered.

> Markers used for matching but not defined _by any key in use_: lgtm
