### ISSUE TITLE
bug(web): `Uncaught (in promise) DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules` on help.keyman.com

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#11467]
```
Uncaught (in promise) DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
    at ge.<anonymous> (https://s.keyman.com/kmw/engine/17.0.325/keymanweb.js:7:25426)
    at Generator.next (<anonymous>)
    at https://s.keyman.com/kmw/engine/17.0.325/keymanweb.js:1:1395
    at new Promise (<anonymous>)
    at Z (https://s.keyman.com/kmw/engine/17.0.325/keymanweb.js:1:1215)
    at ge.allLoadedPromise (https://s.keyman.com/kmw/engine/17.0.325/keymanweb.js:7:25332)
    at VisualKeyboard.<anonymous> (https://s.keyman.com/kmw/engine/17.0.325/keymanweb.js:23:1158)
    at Generator.next (<anonymous>)
    at https://s.keyman.com/kmw/engine/17.0.325/keymanweb.js:1:1395
    at new Promise (<anonymous>)
    at Z (https://s.keyman.com/kmw/engine/17.0.325/keymanweb.js:1:1215)
    at MutationObserver.detectAndHandleInsertion (https://s.keyman.com/kmw/engine/17.0.325/keymanweb.js:23:1080)
```

e.g. https://help.keyman.com/keyboard/basic_kbdhe220/1.1/basic_kbdhe220

Manifests visually with two issues:
* Oversized fonts
* Missing special keys font

![image](https://github.com/keymanapp/keyman/assets/4498365/5bc520ba-c85e-44f0-b48d-ff051e9782c9)

**Comment by jahorton** [comment]
Ah, because it's dealing with a cross-origin stylesheet.   My normal test pattern against that tests against local stylesheets first, which wouldn't have caught this.  Sadly, that makes detecting stylesheet-load more tricky, but I'll figure something out.

**Comment by mcdurdin** [comment]
Ref: https://community.software.sil.org/t/keymanhelp-osk-images-not-appearing-as-expected/8754/2
