### ISSUE TITLE
bug(common): npm ci failing with `Error: Cannot find module './binding.js'`

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#11609]
At least three separate builds against master, on three different build agents, have now failed with the following error:

```
[13:25:36] :	 [Step 5/7] [common/tools/sourcemap-path-remapper] dependency build, started by web/src/tools/building/sourcemap-root
[13:25:36] :	 [Step 5/7] [common/tools/sourcemap-path-remapper] build.sh parameters: <configure build --debug --deps --builder-dep-parent web/src/tools/building/sourcemap-root>
[13:25:36] :	 [Step 5/7] [common/tools/sourcemap-path-remapper] ## configure starting...
[13:25:39]W:	 [Step 5/7] npm WARN skipping integrity check for git dependency ssh://git@github.com/keymanapp/dependency-node-xml2js.git 
[13:25:39]W:	 [Step 5/7] npm WARN skipping integrity check for git dependency ssh://git@github.com/keymanapp/dependency-restructure.git 
[13:25:39]W:	 [Step 5/7] npm WARN skipping integrity check for git dependency ssh://git@github.com/keymanapp/dependency-restructure.git 
[13:25:44]W:	 [Step 5/7] npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
[13:26:21]W:	 [Step 5/7] npm ERR! code 1
[13:26:21]W:	 [Step 5/7] npm ERR! git dep preparation failed
[13:26:21]W:	 [Step 5/7] npm ERR! command /home/bob/.nvm/versions/node/v18.19.0/bin/node /home/bob/.nvm/versions/node/v18.19.0/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/bob/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
[13:26:21]W:	 [Step 5/7] npm ERR! npm WARN using --force Recommended protections disabled.
[13:26:21]W:	 [Step 5/7] npm ERR! npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
[13:26:21]W:	 [Step 5/7] npm ERR! npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
[13:26:21]W:	 [Step 5/7] npm ERR! npm WARN deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR! code 1
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR! path /home/bob/.npm/_cacache/tmp/git-clone4LVQCh/node_modules/@swc/core
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR! command failed
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR! command sh -c node postinstall.js
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR! Error: Cannot find module './binding.js'
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR! Require stack:
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR! - /home/bob/.npm/_cacache/tmp/git-clone4LVQCh/node_modules/@swc/core/postinstall.js
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!     at Module._load (node:internal/modules/cjs/loader:975:27)
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!     at Module.require (node:internal/modules/cjs/loader:1225:19)
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!     at require (node:internal/modules/helpers:177:18)
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!     at /home/bob/.npm/_cacache/tmp/git-clone4LVQCh/node_modules/@swc/core/postinstall.js:136:23
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!     at Generator.next (<anonymous>)
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!     at /home/bob/.npm/_cacache/tmp/git-clone4LVQCh/node_modules/@swc/core/postinstall.js:85:74
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!     at new Promise (<anonymous>)
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!     at __awaiter (/home/bob/.npm/_cacache/tmp/git-clone4LVQCh/node_modules/@swc/core/postinstall.js:64:16)
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!     at validateBinary (/home/bob/.npm/_cacache/tmp/git-clone4LVQCh/node_modules/@swc/core/postinstall.js:119:5) {
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!   code: 'MODULE_NOT_FOUND',
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!   requireStack: [
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!     '/home/bob/.npm/_cacache/tmp/git-clone4LVQCh/node_modules/@swc/core/postinstall.js'
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!   ]
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR! }
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR! @swc/core was not able to resolve native bindings installation. It'll try to use @swc/wasm as fallback instead.
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR! node:internal/modules/cjs/loader:437
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!       const err = new Error(
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!                   ^
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR! 
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR! Error: Cannot find module '/home/bob/.npm/_cacache/tmp/git-clone4LVQCh/node_modules/@swc/core/src/index.js'. Please verify that the package.json has a valid "main" entry
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!     at tryPackage (node:internal/modules/cjs/loader:437:19)
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!     at Module._findPath (node:internal/modules/cjs/loader:705:18)
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1120:27)
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!     at Function.resolve (node:internal/modules/helpers:188:19)
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!     at /home/bob/.npm/_cacache/tmp/git-clone4LVQCh/node_modules/@swc/core/postinstall.js:184:34
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!     at Generator.next (<anonymous>)
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!     at /home/bob/.npm/_cacache/tmp/git-clone4LVQCh/node_modules/@swc/core/postinstall.js:85:74
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!     at new Promise (<anonymous>)
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!     at __awaiter (/home/bob/.npm/_cacache/tmp/git-clone4LVQCh/node_modules/@swc/core/postinstall.js:64:16)
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!     at validateBinary (/home/bob/.npm/_cacache/tmp/git-clone4LVQCh/node_modules/@swc/core/postinstall.js:119:5) {
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!   code: 'MODULE_NOT_FOUND',
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!   path: '/home/bob/.npm/_cacache/tmp/git-clone4LVQCh/node_modules/@swc/core/package.json',
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR!   requestPath: '@swc/core'
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR! }
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR! 
[13:26:21]W:	 [Step 5/7] npm ERR! npm ERR! Node.js v18.19.0
```

* https://build.palaso.org/buildConfiguration/KeymanAndroid_TestPullRequests/467039?buildTab=log&linesState=367&logView=flowAware&focusLine=391
* https://build.palaso.org/buildConfiguration/Keyman_iOS_TestPullRequests/467045?buildTab=log&linesState=108&logView=flowAware&focusLine=202
* https://build.palaso.org/buildConfiguration/Keymanweb_TestPullRequests/467052?buildTab=log&linesState=95&logView=flowAware&focusLine=209

**Comment by mcdurdin** [comment]
Also:

* https://build.palaso.org/buildConfiguration/Keyman_Common_KPAPI_TestPullRequests_Linux/467049?buildTab=log&linesState=151&logView=flowAware
* https://build.palaso.org/buildConfiguration/Keyman_Common_KPAPI_TestPullRequests_macOS/467051?buildTab=log&linesState=87&logView=flowAware
* https://build.palaso.org/buildConfiguration/Keyman_Common_KPAPI_TestPullRequests_WASM/467054?buildTab=log&linesState=149&logView=flowAware
* https://build.palaso.org/buildConfiguration/Keyman_iOS_TestPullRequests/466997?buildTab=log&linesState=105.272&logView=flowAware
* https://build.palaso.org/buildConfiguration/Keyman_Test_Common_Mac/467022?buildTab=log&linesState=89&logView=flowAware
* https://build.palaso.org/buildConfiguration/Keyman_iOS_TestPullRequests/467024?buildTab=log&linesState=105.272&logView=flowAware
* https://build.palaso.org/buildConfiguration/Keyman_iOS_TestSamplesAndTestProjects/467009?buildTab=log&linesState=84&logView=flowAware
* https://build.palaso.org/buildConfiguration/Keyman_Test_Common_Web/467041?buildTab=log&linesState=110&logView=flowAware
* https://build.palaso.org/buildConfiguration/Keyman_Test_Common_Mac/467043?buildTab=log&linesState=87&logView=flowAware

Looks like it is restricted to macOS/Linux environments, relating to package `@swc/core`.

**Comment by mcdurdin** [comment]
Looks like this: https://github.com/swc-project/swc/issues/8996

Workaround is apparently to add an override in package.json to version 1.5.7.

**Comment by mcdurdin** [comment]
https://github.com/swc-project/swc/commit/4c0b2e81d92e317b2c7931b3098e608eae61f207 may have fixed this.

I don't know how to avoid this kind of problem in the future. It seems that `npm install` does not add version information for peer dependencies?

In package-lock.json, `node_modules/ts-node` has:

```
      "peerDependencies": {
        "@swc/core": ">=1.2.50",
```

But that's the only (relevant) reference to `@swc/core`. I would have thought that there should be a `node_modules/@swc/core` entry in package-lock.json after `npm install`?

**Comment by mcdurdin** [comment]
Weirdly, `@swc/core` is not installed in node_modules on my Windows or Ubuntu machines, npm 10.7.0 in both cases now. So ... what's going on?

**Comment by mcdurdin** [comment]
Seems to be fixed in @swc/core
