### ISSUE TITLE
bug(common): @swc/core breaking on Windows agents

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#11614]
After the issues earlier today with @swc/core in #11609, we now are starting to see similar problems on Windows agents. The underlying issue is that the version of ts-node we depend on has a peer dependency on @swc/core with a version ">=1.2.50", and @swc/core seems to have very rapid pushes to public which are inadequately tested.

https://build.palaso.org/buildConfiguration/Keyman_Common_KPAPI_TestPullRequests_Windows/467276?buildTab=log&linesState=98&logView=flowAware

```
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR! code 1
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR! path C:\Users\bob\AppData\Local\npm-cache\_cacache\tmp\git-cloneaQpkEg\node_modules\@swc\core
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR! command failed
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node postinstall.js
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR! Error: Failed to load native binding
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     at Object.<anonymous> (C:\Users\bob\AppData\Local\npm-cache\_cacache\tmp\git-cloneaQpkEg\node_modules\@swc\core\binding.js:339:15)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1256:14)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     at Module.load (node:internal/modules/cjs/loader:1119:32)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     at Module._load (node:internal/modules/cjs/loader:960:12)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     at Module.require (node:internal/modules/cjs/loader:1143:19)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     at require (node:internal/modules/cjs/helpers:110:18)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     at C:\Users\bob\AppData\Local\npm-cache\_cacache\tmp\git-cloneaQpkEg\node_modules\@swc\core\postinstall.js:81:19
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     at Generator.next (<anonymous>)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     at C:\Users\bob\AppData\Local\npm-cache\_cacache\tmp\git-cloneaQpkEg\node_modules\@swc\core\postinstall.js:31:71 {
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!   [cause]: [
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     Error: Cannot find module './swc.win32-x64-msvc.node'
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     Require stack:
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     - C:\Users\bob\AppData\Local\npm-cache\_cacache\tmp\git-cloneaQpkEg\node_modules\@swc\core\binding.js
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     - C:\Users\bob\AppData\Local\npm-cache\_cacache\tmp\git-cloneaQpkEg\node_modules\@swc\core\postinstall.js
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!         at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!         at Module._load (node:internal/modules/cjs/loader:922:27)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!         at Module.require (node:internal/modules/cjs/loader:1143:19)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!         at require (node:internal/modules/cjs/helpers:110:18)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!         at requireNative (C:\Users\bob\AppData\Local\npm-cache\_cacache\tmp\git-cloneaQpkEg\node_modules\@swc\core\binding.js:96:24)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!         at Object.<anonymous> (C:\Users\bob\AppData\Local\npm-cache\_cacache\tmp\git-cloneaQpkEg\node_modules\@swc\core\binding.js:312:17)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!         at Module._compile (node:internal/modules/cjs/loader:1256:14)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!         at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!         at Module.load (node:internal/modules/cjs/loader:1119:32)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!         at Module._load (node:internal/modules/cjs/loader:960:12) {
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!       code: 'MODULE_NOT_FOUND',
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!       requireStack: [Array]
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     },
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     Error: Cannot find module '@swc/core-win32-x64-msvc'
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     Require stack:
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     - C:\Users\bob\AppData\Local\npm-cache\_cacache\tmp\git-cloneaQpkEg\node_modules\@swc\core\binding.js
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     - C:\Users\bob\AppData\Local\npm-cache\_cacache\tmp\git-cloneaQpkEg\node_modules\@swc\core\postinstall.js
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!         at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!         at Module._load (node:internal/modules/cjs/loader:922:27)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!         at Module.require (node:internal/modules/cjs/loader:1143:19)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!         at require (node:internal/modules/cjs/helpers:110:18)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!         at requireNative (C:\Users\bob\AppData\Local\npm-cache\_cacache\tmp\git-cloneaQpkEg\node_modules\@swc\core\binding.js:101:24)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!         at Object.<anonymous> (C:\Users\bob\AppData\Local\npm-cache\_cacache\tmp\git-cloneaQpkEg\node_modules\@swc\core\binding.js:312:17)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!         at Module._compile (node:internal/modules/cjs/loader:1256:14)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!         at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!         at Module.load (node:internal/modules/cjs/loader:1119:32)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!         at Module._load (node:internal/modules/cjs/loader:960:12) {
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!       code: 'MODULE_NOT_FOUND',
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!       requireStack: [Array]
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     }
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!   ]
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR! }
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR! @swc/core was not able to resolve native bindings installation. It'll try to use @swc/wasm as fallback instead.
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR! node:internal/modules/cjs/loader:1077
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!   const err = new Error(message);
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!               ^
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR! 
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR! Error: Cannot find module 'C:\Users\bob\AppData\Local\npm-cache\_cacache\tmp\git-cloneaQpkEg\node_modules\@swc\core\src\package.json'
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR! Require stack:
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR! - C:\Users\bob\AppData\Local\npm-cache\_cacache\tmp\git-cloneaQpkEg\node_modules\@swc\core\postinstall.js
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     at Module._load (node:internal/modules/cjs/loader:922:27)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     at Module.require (node:internal/modules/cjs/loader:1143:19)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     at require (node:internal/modules/cjs/helpers:110:18)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     at C:\Users\bob\AppData\Local\npm-cache\_cacache\tmp\git-cloneaQpkEg\node_modules\@swc\core\postinstall.js:114:25
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     at Generator.next (<anonymous>)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     at C:\Users\bob\AppData\Local\npm-cache\_cacache\tmp\git-cloneaQpkEg\node_modules\@swc\core\postinstall.js:31:71
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     at new Promise (<anonymous>)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     at __awaiter (C:\Users\bob\AppData\Local\npm-cache\_cacache\tmp\git-cloneaQpkEg\node_modules\@swc\core\postinstall.js:27:12)
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     at validateBinary (C:\Users\bob\AppData\Local\npm-cache\_cacache\tmp\git-cloneaQpkEg\node_modules\@swc\core\postinstall.js:66:30) {
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!   code: 'MODULE_NOT_FOUND',
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!   requireStack: [
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!     'C:\\Users\\bob\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-cloneaQpkEg\\node_modules\\@swc\\core\\postinstall.js'
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR!   ]
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR! }
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR! 
[13:08:08]W:	 [Step 1/1] npm ERR! npm ERR! Node.js v18.17.0
```

We may be able to update ts-node in our local package.json? Will test this.

**Comment by mcdurdin** [comment]
This has also been resolved upstream.
