### ISSUE TITLE
bug(web): undefined reading 'deleteLeft' causing crash in Android app

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#12494]
@dinakaranr recorded and reported this issue using the current Keyman for Android 18.0 alpha 
(I can repro on 18.0.117-alpha)

Steps to repro:

1. In the Keyman app with the default sil_euro_latin keyboard
2. Longpress <kbd>g</kbd> --> `g̃`
3. Longpress <kbd>h</kbd> --> `ḥ`
4. Longpress <kbd>j</kbd> --> `ĵ`
5. Flick down on <kbd>c</kbd> --> `'`
6. Flick down on <kbd>v</kbd> --> Javascript error

The chrome dev tools gives the following error
```
@keymanapp/keyman/we…es/src/common.ts:40 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'deleteLeft')
    at buildMergedTransform (@@keymanapp/keyman/web/src/engine/predictive-text/templates/src/common.ts:40:43)
    at ContextTracker.attemptMatchContext (@keymanapp/keyman/web/src/engine/predictive-text/templates/src/common.ts:444:57)
    at _ContextTracker.analyzeState (@keymanapp/keyman/web/src/engine/predictive-text/worker-thread/src/main/correction/context-tracker.…:673:37)
    at @keymanapp/keyman/we…t-helpers.ts:175:48
    at Generator.next (<anonymous>)
    at blob:null/1b8791be-3…-49f3ec17d480:49:63
    at new Promise (<anonymous>)
    at __async (blob:null/1b8791be-3…-49f3ec17d480:33:12)
    at correctAndEnumerate (@keymanapp/keyman/we…ct-helpers.ts:103:4)
    at _ModelCompositor.<anonymous> (@keymanapp/keyman/we…ompositor.ts:122:56)
```

**Comment by darcywong00** [comment]
His video was too large to attach to GH so I will split it...

**Comment by ermshiperete** [comment]
To get the error it is sufficient to do steps 5 and 6.

**Comment by darcywong00** [comment]
Since this is web, I'll unassign myself on this. @ermshiperete can get to it A18S19

**Comment by ermshiperete** [comment]
I'm no longer able to reproduce this. @dinakaranr Can you please re-test and see if this works now for you as well?

**Comment by dinakaranr** [comment]
I tested this issue with the attached "18.0.162-alpha" build on the Andoird 14 and am sharing my observations here. I reproduced this crash using the "sil_euro_latin" keyboard.
Open the keyman app in the Android mobile app. Added a sentence. added letters this order g --> g̃, h --> ḥ, j --> ĵ, c --> ', v --> "
Here, Crash appeared it
Please take a look at the attached video file(Android14_Keyman18.0.162Alpha.mp4). Thank you.
https://github.com/user-attachments/assets/a4067af7-8582-4b67-bc40-e6f88b1b2671

**Comment by jahorton** [comment]
Here's the source of the `null`:

https://github.com/keymanapp/keyman/blob/d7025539f9e024659ae010fb48c2d1154ceea29e/web/src/engine/predictive-text/worker-thread/src/main/correction/context-tracker.ts#L426-L432

This block is within a loop:

https://github.com/keymanapp/keyman/blob/d7025539f9e024659ae010fb48c2d1154ceea29e/web/src/engine/predictive-text/worker-thread/src/main/correction/context-tracker.ts#L416-L418

It's iterating over three items when following the repro at the top, with edit path `[insert, insert, substitution]`, but the `transformSequenceDistribution` here has only one entry.  I'd say that _this_ is where the bug is.

**Comment by ermshiperete** [comment]
No wonder I'm not able to reproduce if I use the wrong test file. Since this is predictive-text related it has to be tested on a page that shows predictions 🤦 . For example "Prediction - robust testing".
