### ISSUE TITLE
bug(ios): Fastlane reporting: Beta App Description is missing. - Beta App Description is required to submit a build for external testing. 

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#12672]
```
 /opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/spaceship/lib/spaceship/connect_api/api_client.rb:223:in `handle_response': [!] Beta App Description is missing. - Beta App Description is required to submit a build for external testing. (Spaceship::UnexpectedResponse)
01:18:18     from /opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/spaceship/lib/spaceship/connect_api/api_client.rb:125:in `post'
01:18:18     from /opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:115:in `post_beta_app_review_submissions'
01:18:18     from /opt/homebrew/Cellar/ruby/3.3.1/lib/ruby/3.3.0/forwardable.rb:240:in `post_beta_app_review_submissions'
```

https://build.palaso.org/buildConfiguration/Keyman_iOS_Master/505271?buildTab=log&linesState=2482&logView=flowAware&focusLine=2540

AFAIK, no changes at our end that might have caused this. 18.0.140-alpha

**Comment by mcdurdin** [comment]
Resolved by adding beta description into build configuration script.
