### ISSUE TITLE
[Android] Crash retrieving missing font

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1478]
KMManager.java line 620
com.tavultesoft.kmea.KMManager.getFontTypeface

https://console.firebase.google.com/u/0/project/kmapro-ee779/crashlytics/app/android:com.tavultesoft.kmapro/issues/5c2dd37df8b88c29630b871c?time=last-seven-days&pli=1

```
Fatal Exception: java.lang.RuntimeException
Font not found /data/user/0/com.tavultesoft.kmapro/app_data/cloud/wookianos.woff

Fatal Exception: java.lang.RuntimeException: Font not found /data/user/0/com.tavultesoft.kmapro/app_data/cloud/wookianos.woff
       at android.graphics.Typeface.createFromFile(Typeface.java:330)
       at android.graphics.Typeface.createFromFile(Typeface.java:313)
       at com.tavultesoft.kmea.KMManager.getFontTypeface(KMManager.java:620)
       at com.tavultesoft.kmea.KMKeyboard.showSubKeys(KMKeyboard.java:706)
       at com.tavultesoft.kmea.KMKeyboard.access$200(KMKeyboard.java:54)
       at com.tavultesoft.kmea.KMKeyboard$2.onLongPress(KMKeyboard.java:156)
       at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:809)
       at android.view.GestureDetector.-wrap0(GestureDetector.java)
       at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:305)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6780)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

This is occurring in the beta version of Keyman for Android 11.0.2050.0

**Comment by darcywong00** [comment]
Fixed in master in #1513
