### ISSUE TITLE
[android] globe button causing 3rd party app to crash

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#2786]
Reported from an email:

> This week I have been updating the Keyman version built into Scripture/Reading/Dictionary App Builder to be Keyman Engine [Android] version 13 - in readiness for version 7.0 of SAB, DAB and RAB. Thank you very much to you and your team for all your work on this!
> There is still the issue of a crash when a user presses the Change Keyboard globe button on the keyboard in an Android app

**Comment by darcywong00** [comment]
User was able to resolve the issue.

The exception was
```
  android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
        at android.app.ContextImpl.startActivity(ContextImpl.java:915)
        at android.app.ContextImpl.startActivity(ContextImpl.java:891)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
        at com.tavultesoft.kmea.KMManager.showKeyboardPicker(KMManager.java:1273)
        at com.tavultesoft.kmea.KMManager$KMInAppKeyboardWebViewClient.shouldOverrideUrlLoading(KMManager.java:1580)
        at com.tavultesoft.kmea.KMManager$KMInAppKeyboardWebViewClient.onPageFinished(KMManager.java:1505)
```

> I was able to fix it by adding this line:
```
   i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
```
for the in-app keyboard in showKeyboardPicker in KMManager.java.
