### ISSUE TITLE
FileUtilsTest JUnit test fails in test_isWelcomeFile (when building on Linux)

### ISSUE THREAD

**Issue by ericjding** [keymanapp/keyman#3052]
KMEA builds successfully on Linux, but the JUnit test suite fails, in the latest master branch:

```
com.tavultesoft.kmea.util.FileUtilsTest > test_isWelcomeFile FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at com.tavultesoft.kmea.util.FileUtilsTest.test_isWelcomeFile(FileUtilsTest.java:268)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

Following the breadcrumbs, I arrived at the addition of these two lines from 74cad36ba996900357df5547107249ae16f41849 in FileUtilsTest.java:

```
    filename = "test\\welcome.htm";
    Assert.assertTrue(FileUtils.isWelcomeFile(filename));
```

This looks suspiciously like a Windows-specific filename format, which is why it fails the JUnit test on Linux (since test_isWelcomeFile() uses File.separator), but I'm not sure what the intention of this change was, so I leave it to wiser and more experienced folks to figure out how to fix. :-)

**Comment by mcdurdin** [comment]
@darcywong00 should be straightforward to resolve I hope.
