### ISSUE TITLE
bug(common): build failed with 'API rate limit exceeded'

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#4061]
```
[05:00:12]The build is removed from the queue to be prepared for the start
[05:00:13]Collecting changes in 2 VCS roots
[05:00:13]Starting the build on the agent "ba-win10-64-pp-602"
[05:00:18]Updating tools for build
[05:00:18]Clearing temporary directory: C:\BuildAgent\temp\buildTmp
[05:00:18]Publishing internal artifacts
[05:00:18]Full checkout enforced. Reason: [Checkout directory is empty or doesn't exist]
[05:00:18]Will perform clean checkout. Reason: Checkout directory is empty or doesn't exist
[05:00:18]Checkout directory: C:\BuildAgent\work\e902ed814d7c1b8
[05:00:18]Updating sources: auto checkout (on agent) (33s)
[05:00:52]Step 1/2: Update history, increment build version and trigger release builds for selected branch (Command Line) (14s)
[05:00:52][Step 1/2] Starting: C:\BuildAgent\temp\agentTmp\custom_script3356737758916797907.cmd
[05:00:52][Step 1/2] in directory: C:\BuildAgent\work\e902ed814d7c1b8\keyman
[05:00:54][Step 1/2] From https://github.com/keymanapp/keyman
[05:00:54][Step 1/2]  * branch                master     -> FETCH_HEAD
[05:00:54][Step 1/2] Already up to date.
[05:00:59][Step 1/2] added 88 packages from 118 contributors and audited 89 packages in 3.511s
[05:00:59][Step 1/2] 
[05:00:59][Step 1/2] 2 packages are looking for funding
[05:00:59][Step 1/2]   run `npm fund` for details
[05:00:59][Step 1/2] 
[05:00:59][Step 1/2] found 1 low severity vulnerability
[05:00:59][Step 1/2]   run `npm audit fix` to fix them, or `npm audit` for details
[05:01:00][Step 1/2] 
[05:01:00][Step 1/2] > @keymanapp/auto-history-action@1.1.3 build:ts C:\BuildAgent\work\e902ed814d7c1b8\keyman\resources\build\version
[05:01:00][Step 1/2] > tsc --project tsconfig.production.json
[05:01:00][Step 1/2] 
[05:01:06][Step 1/2] # Validating history for 14.0.195
[05:01:06][Step 1/2] An unexpected error occurred: API rate limit exceeded, GraphqlError: API rate limit exceeded
[05:01:06][Step 1/2]     at C:\BuildAgent\work\e902ed814d7c1b8\keyman\resources\build\version\node_modules\@octokit\graphql\dist-node\index.js:47:13
[05:01:06][Step 1/2]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[05:01:06][Step 1/2]     at async getPullRequestInformation (C:\BuildAgent\work\e902ed814d7c1b8\keyman\resources\build\version\lib\fixupHistory.js:9:22)
[05:01:06][Step 1/2]     at async Object.exports.fixupHistory (C:\BuildAgent\work\e902ed814d7c1b8\keyman\resources\build\version\lib\fixupHistory.js:131:23)
[05:01:06][Step 1/2]     at async main (C:\BuildAgent\work\e902ed814d7c1b8\keyman\resources\build\version\lib\index.js:40:23).
[05:01:06][Step 1/2] Skipping version increment from 14.0.195: no recently merged pull requests were found
[05:01:06][Step 1/2]  [H [J
[05:01:06][Step 1/2] Process exited with code 0
[05:01:06]Step 2/2: Upload HISTORY.md to downloads.keyman.com (1) (PowerShell) (3s)
[05:01:10]Publishing internal artifacts (5s)
[05:01:15]Build finished
```

**Comment by mcdurdin** [comment]
I just split status.keyman.com onto its own github account so it wouldn't affect the rate limit for builds.
