### ISSUE TITLE
bug(android/engine): Null pointer exception on HashMap.getOrDefault()

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#4269]
Generated from Play Store 14.0 pre-release launch report

On 14.0.222 beta
Android 5.0 (API 21)

```
FATAL EXCEPTION: Thread-2
Process: com.tavultesoft.kmapro, PID: 12383
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.getOrDefault(java.lang.Object, java.lang.Object)' on a null object reference
	at com.tavultesoft.kmea.util.MapCompat.getOrDefault(MapCompat.java:17)
	at com.tavultesoft.kmapro.KeyboardSettingsActivity$2.onItemClick(KeyboardSettingsActivity.java:166)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1158)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3153)
	at android.widget.AbsListView$3.run(AbsListView.java:4068)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:11)
	at androidx.test.espresso.base.UiControllerImpl.n(UiControllerImpl.java:6)
	at androidx.test.espresso.base.UiControllerImpl.m(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.e(UiControllerImpl.java:8)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:4)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:4)
	at androidx.test.espresso.ViewInteraction.a(Unknown Source:137)
	at androidx.test.espresso.ViewInteraction$1.call(Unknown Source:4)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6647)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

**Comment by darcywong00** [comment]
Closed by #4664
