### ISSUE TITLE
bug(core): could not build using meson installed from MSI

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#7349]
Windows 11 Home.  

Installed meson from its MSI <https://github.com/mesonbuild/meson/releases/tag/0.63.2> and the build did not work.

Uninstalling meson and installing via `pip` (as the docs say) worked fine.

```
>>> MALLOC_PERTURB_=216 C:\Program Files\Meson\meson.exe runpython -c import sys; a = open(sys.argv[1], 'r').read(); b = open(sys.argv[2], 'r').read(); exit(not (a==b)) jsontest.json C:/projects/keyman/keyman/core/tests/standards/jsontest.json
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
stdout:

ERROR: Unhandled python exception
No such file or directory - (2, 'No such file or directory')
this is probably not a Meson bug.
stderr:
Traceback (most recent call last):
  File "mesonbuild\mesonmain.py", line 153, in run
  File "mesonbuild\mesonmain.py", line 106, in run_runpython_command
  File "<string>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'runpython'
―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――  
```

dunno what this runpython thing was supposed to be, but it's not a happy camper.

**Comment by mcdurdin** [comment]
Inclined to note this issue but close it because it's not a supported build environment 😉
