### ISSUE TITLE
feat(developer): Add hints, warnings, and errors to ts-based package compiler

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#8150]
We need to ensure that all the error checking that is currently done in the pascal-based package compiler is replicated in the typescript version.

---

- [x] Note: ts-based package compiler needs to have significant additional work on it, as we do not currently emit any warnings or errors. Suggest bundling this error into that work.
- [x] #8657
- [x] #8658 (CompilePackage.pas:155)
- [x] #8659
- [ ] #7353
- [x] #8730
- [x] #8752
- [x] #8753
- [x] #8754
- [x] #8756
- [x] #8765
- [x] #8772
- [x] #8773
- [x] #8766
- [x] #8774
- [x] #8775
- [x] #8779
- [x] #8780
- [x] #8776
- [x] #8777
- [x] #8767
- [x] #8643 (CompilePackage.pas:293)
- [x] #8787
- [x] #8788
- [x] #8789
- [x] #8790
- [x] #8768
- [x] #8782
- [x] #8781
- [x] #8731
- [ ] #8672
- [x] #8791

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/issues/8119#issuecomment-1413295606_

**Comment by mcdurdin** [comment]
e.g. this should be a friendly error message:

```
C:\Projects\keymanapp\keyboards\release\k\khmer_angkor\source>kmc build khmer_angkor.kps
Building khmer_angkor.kps
Error: ENOENT: no such file or directory, open 'C:\Projects\keymanapp\keyboards\release\k\khmer_angkor\build\khmer_angkor.js'
    at Object.openSync (node:fs:601:3)
    at Module.readFileSync (node:fs:469:35)
    at file:///C:/Users/mcdurdin/AppData/Roaming/npm/node_modules/@keymanapp/kmc/node_modules/@keymanapp/kmc-package/build/src/kmp-compiler.js:222:27
    at Array.forEach (<anonymous>)
    at KmpCompiler.buildKmpFile (file:///C:/Users/mcdurdin/AppData/Roaming/npm/node_modules/@keymanapp/kmc/node_modules/@keymanapp/kmc-package/build/src/kmp-compiler.js:198:20)
    at BuildPackage.build (file:///C:/Users/mcdurdin/AppData/Roaming/npm/node_modules/@keymanapp/kmc/build/src/activities/BuildPackage.js:19:38)
    at build (file:///C:/Users/mcdurdin/AppData/Roaming/npm/node_modules/@keymanapp/kmc/build/src/commands/build.js:38:26)
    at Command.<anonymous> (file:///C:/Users/mcdurdin/AppData/Roaming/npm/node_modules/@keymanapp/kmc/build/src/commands/build.js:18:20)
    at Command.listener [as _actionHandler] (C:\Users\mcdurdin\AppData\Roaming\npm\node_modules\@keymanapp\kmc\node_modules\commander\lib\command.js:482:17)
    at C:\Users\mcdurdin\AppData\Roaming\npm\node_modules\@keymanapp\kmc\node_modules\commander\lib\command.js:1283:65 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Projects\\keymanapp\\keyboards\\release\\k\\khmer_angkor\\build\\khmer_angkor.js'
}
```

**Comment by mcdurdin** [comment]
Per the OP, #8151 needs to be implemented in kmc-package.

**Comment by mcdurdin** [comment]
```
AssertionError: expected [Function] to not throw an error but 'TypeError: Cannot read properties of undefined (reading \'executeProgram\')' was thrown
```

Note: executeProgram should be optional (all of Options key is optional)

**Comment by mcdurdin** [comment]
See also #7353

**Comment by mcdurdin** [comment]
Marking this as done. #7353 is mostly around regression-testing the new compiler, which will come later. All other hints and warnings have been implemented.
