### ISSUE TITLE
chore(developer): kmc - missing file should give friendly error

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#8657]
e.g. this should be a friendly error message (17.0.89-alpha):

```
C:\Projects\keymanapp\keyboards\release\k\khmer_angkor\source>kmc build khmer_angkor.kps
Building khmer_angkor.kps
Error: ENOENT: no such file or directory, open 'C:\Projects\keymanapp\keyboards\release\k\khmer_angkor\build\khmer_angkor.js'
    at Object.openSync (node:fs:601:3)
    at Module.readFileSync (node:fs:469:35)
    at file:///C:/Users/mcdurdin/AppData/Roaming/npm/node_modules/@keymanapp/kmc/node_modules/@keymanapp/kmc-package/build/src/kmp-compiler.js:222:27
    at Array.forEach (<anonymous>)
    at KmpCompiler.buildKmpFile (file:///C:/Users/mcdurdin/AppData/Roaming/npm/node_modules/@keymanapp/kmc/node_modules/@keymanapp/kmc-package/build/src/kmp-compiler.js:198:20)
    at BuildPackage.build (file:///C:/Users/mcdurdin/AppData/Roaming/npm/node_modules/@keymanapp/kmc/build/src/activities/BuildPackage.js:19:38)
    at build (file:///C:/Users/mcdurdin/AppData/Roaming/npm/node_modules/@keymanapp/kmc/build/src/commands/build.js:38:26)
    at Command.<anonymous> (file:///C:/Users/mcdurdin/AppData/Roaming/npm/node_modules/@keymanapp/kmc/build/src/commands/build.js:18:20)
    at Command.listener [as _actionHandler] (C:\Users\mcdurdin\AppData\Roaming\npm\node_modules\@keymanapp\kmc\node_modules\commander\lib\command.js:482:17)
    at C:\Users\mcdurdin\AppData\Roaming\npm\node_modules\@keymanapp\kmc\node_modules\commander\lib\command.js:1283:65 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Projects\\keymanapp\\keyboards\\release\\k\\khmer_angkor\\build\\khmer_angkor.js'
}
```

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/issues/8150#issuecomment-1512450078_

**Comment by mcdurdin** [comment]
Fixed in [#8627 kmp-compiler.ts:268](https://github.com/keymanapp/keyman/pull/8627/files#diff-3d63e15b45d33e4c5dbea851c30305237d14bce2949484bec43dd703d32291dbR268)
