### ISSUE TITLE
bug(developer): node v16 fails tests

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#8950]
Problems trying to run `kmc` with node v16:

> Could not instantiate WASM compiler module: `unexpected section <Tag>`

passes with v18

```
Program cp found: YES (/usr/local/opt/coreutils/libexec/gnubin/cp)
Configuring k_002_tinyu32.kmx with command
Running command: /Users/srl295/.nvm/versions/node/v16.20.0/bin/node /Users/srl295/src/keymanapp/keyman/core/../developer/src/kmc build /Users/srl295/src/keymanapp/keyman/core/tests/unit/ldml/keyboards/k_002_tinyu32.xml --out-file /Users/srl295/src/keymanapp/keyman/core/build/wasm/release/tests/unit/ldml/keyboards/k_002_tinyu32.kmx
--- stdout ---
INFO 5002: Building /Users/srl295/src/keymanapp/keyman/core/tests/unit/ldml/keyboards/k_002_tinyu32.xml
FATAL 403001: Could not instantiate WASM compiler module or initialization failed: RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): unexpected section <Tag> (enable with --experimental-wasm-eh) @+2187). Build with -sASSERTIONS for more info.

Call stack:
RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): unexpected section <Tag> (enable with --experimental-wasm-eh) @+2187). Build with -sASSERTIONS for more info.
    at abort (file:///Users/srl295/src/keymanapp/keyman/developer/src/kmc-kmn/build/src/import/kmcmplib/wasm-host.js:146:19)
    at file:///Users/srl295/src/keymanapp/keyman/developer/src/kmc-kmn/build/src/import/kmcmplib/wasm-host.js:184:326
FATAL 400017: The compiler for 'vars' failed to initialize.
FATAL 405001: Unexpected exception: Error: Internal error: section bksp depends on uninitialized dependency vars

Call stack:
Error: Internal error: section bksp depends on uninitialized dependency vars
    at file:///Users/srl295/src/keymanapp/keyman/developer/src/kmc-ldml/build/src/compiler/compiler.js:144:31
    at Array.forEach (<anonymous>)
    at LdmlKeyboardCompiler.compile (file:///Users/srl295/src/keymanapp/keyman/developer/src/kmc-ldml/build/src/compiler/compiler.js:140:44)
    at async buildLdmlKeyboardToMemory (file:///Users/srl295/src/keymanapp/keyman/developer/src/kmc/build/src/commands/build/BuildLdmlKeyboard.js:55:15)
    at async BuildLdmlKeyboard.build (file:///Users/srl295/src/keymanapp/keyman/developer/src/kmc/build/src/commands/build/BuildLdmlKeyboard.js:15:31)
    at async build (file:///Users/srl295/src/keymanapp/keyman/developer/src/kmc/build/src/commands/build.js:55:22)
    at async Command.<anonymous> (file:///Users/srl295/src/keymanapp/keyman/developer/src/kmc/build/src/commands/build.js:22:18)
    at async Command.parseAsync (/Users/srl295/src/keymanapp/keyman/developer/src/kmc/node_modules/commander/lib/command.js:935:5)
```

**Comment by mcdurdin** [comment]
Our minimum version of Node is 18 (LTS) for Keyman 17:

https://github.com/keymanapp/keyman/blob/1d3fc99b28e4106aa69499d698fd529b08c6282e/docs/build/windows.md#L186

The docs/build pages need consolidation once more, as we should have a single file with our required versions, and then make the various platform files about configuration, rather than version.

**Comment by mcdurdin** [comment]
Closing this as by-design
