### ISSUE TITLE
bug(developer): kmc-kmn does not have callstack symbols for wasm errors 🗜

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#9113]
* For release builds, no symbols appear to be generated, so `--enable-source-maps` doesn't work.
* We also should make sure these errors are reported to sentry.

```
INFO 5002: Building release/v/vietnamese_telex/vietnamese_telex.kpj
INFO 5002: Building C:\Projects\keyman\keyboards\release\v\vietnamese_telex\source\vietnamese_telex.kmn
Aborted(OOM)
FATAL 402900: Unexpected exception: RuntimeError: unreachable

Call stack:
RuntimeError: unreachable
    at wasm://wasm/0011e4b2:wasm-function[948]:0x3ae13
    at ___trap (file:///C:/Projects/keyman/app/developer/src/kmc-kmn/build/src/import/kmcmplib/wasm-host.js:1164:80)
    at abort (file:///C:/Projects/keyman/app/developer/src/kmc-kmn/build/src/import/kmcmplib/wasm-host.js:241:13)
    at abortOnCannotGrowMemory (file:///C:/Projects/keyman/app/developer/src/kmc-kmn/build/src/import/kmcmplib/wasm-host.js:1046:59)
    at _emscripten_resize_heap (file:///C:/Projects/keyman/app/developer/src/kmc-kmn/build/src/import/kmcmplib/wasm-host.js:1047:125)
    at wasm://wasm/0011e4b2:wasm-function[352]:0x22b62
    at wasm://wasm/0011e4b2:wasm-function[348]:0x20deb
    at wasm://wasm/0011e4b2:wasm-function[851]:0x38770
    at wasm://wasm/0011e4b2:wasm-function[70]:0x9464
    at wasm://wasm/0011e4b2:wasm-function[76]:0xd541
```

**Comment by mcdurdin** [comment]
Waiting on:
* wasm-split: https://github.com/getsentry/symbolicator/issues/969#issuecomment-1633606623
* sentry-cli: https://github.com/getsentry/sentry-cli/issues/1682 (fixed but not deployed at time of writing)
